'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from 'react-bootstrap';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'The fist next app with ts',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <Container>{children}</Container>
        <AppFooter />
      </body>
    </html>
  );
}
